import "../styles/globals.css";
import Head from "next/head";
import dynamic from 'next/dynamic';

const ChatBot = dynamic(import('../components/chatbot'), { ssr: false });


// function MyApp({ Component, pageProps }) {
function MyApp() {
  return (
    <>
      <Head>
        <title>ChatBot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ChatBot />
    </>
  );
}

export default MyApp;
